import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import about_us from "../public/img/about-us.png";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link
					href='https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap'
					rel='stylesheet'
				/>
				<link
					rel='stylesheet'
					href='https://use.fontawesome.com/releases/v5.15.4/css/all.css'
					integrity='sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm'
					crossorigin='anonymous'
				/>

				<script src='/script/jquery-3.6.0.min.js' />
				<script src='/script/bootstrap.bundle.min.js' />
				<script src='/script/script.js' />
			</Head>

			<section className='aboutus_sec p-top p-bottom'>
				<div className='container'>
					<div className='row'>
						<div className='col-md-12'>
							<div className='heading'>
								<h2>About Us</h2>
							</div>
						</div>
					</div>

					<div className='row'>
						<div className='col-md-12'>
							<div className='about-column'>
								<div className='about-img'>
									<Image src={about_us} layout='responsive' alt='' />
								</div>
								<div className='about_content'>
									<h4>WELCOME TO Najmat Al Rawnaq</h4>
									<h2>About Najmat Al Rawnaq</h2>
									<p>
										{" "}
										Najmat Al Rawnaq is an integrated 360 degree communication
										agency brimming with ideas and enthusiasm to create
										corporate identities. We are focused on Traditional Media,
										Ambient Media, Transit Media, Street Furniture Media and
										many more ways of media.
									</p>
									<p>
										{" "}
										Najmat Al Rawnaq has garnered extensive experience in
										outdoor advertising in a very short span of time
										(billboards, bus shelters, transit advertising and
										innovations), especially in state and national level
										highways. Our contracts, including street advertising in
										UAE, provide options that are expected from any outdoor
										advertising company, thereby guaranteeing unmatched
										visibility for your brand, product or services.
									</p>
								</div>
								<div className='about_content-right'>
									<h2>Why Najmat Al Rawnaq Limited</h2>
									<p>
										People spend 70% of their time out of home. We are focused
										on creating platforms that reach a wide range of audiences
										on their commute time.
									</p>
									<p>
										We showcase your brand at the right time among the right
										audience
									</p>
									<p>
										We are equip with experienced professionals who have
										exploding ideas for your fruitful presence
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</>
	);
}
