import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Hero_sec from "@/components/home_layout/hero_sec/hero_sec";
import Our_services from "@/components/home_layout/our_services/our_services";
import Why_Choose from "@/components/home_layout/Why_Choose/Why_Choose";
import Our_projects from "@/components/home_layout/our_projects/our_projects";
import Contact_us from "@/components/home_layout/contact_us/contact_us";
import Our_clients from "@/components/home_layout/our_clients/our_clients";

import React, { useEffect, useState } from "react";
import axios from "axios";
import { baseUrl } from "../configs";

export default function Home() {
	const [banner, setBanner] = useState("");
	const [project, setproject] = useState("");
	const [service, setservice] = useState("");

	useEffect(() => {
		(async function () {
			const response = await axios.get(`${baseUrl}/home/banner`);
			const response1 = await axios.get(`${baseUrl}/home/service`);
			const response2 = await axios.get(`${baseUrl}/home/project`);

			if (
				response.data.status &&
				response1.data.status &&
				response2.data.status
			) {
				setBanner(response.data.data);
				setservice(response1.data.data);
				setproject(response2.data.data);
			}
		})();
	}, []);

	return (
		<>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link
					href='https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap'
					rel='stylesheet'
				/>
				<link
					rel='stylesheet'
					href='https://use.fontawesome.com/releases/v5.15.4/css/all.css'
					integrity='sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm'
					crossorigin='anonymous'
				/>

				<script src='/script/jquery-3.6.0.min.js' />
				<script src='/script/bootstrap.bundle.min.js' />
				<script src='/script/script.js' />
			</Head>

			<Hero_sec banner={banner} />
			<Our_services service={service} />
			<Why_Choose />
			<Our_projects project={project} />
			<Contact_us />
			<Our_clients />
		</>
	);
}
